development:
  url: http://nuntium.instedd.org
  account: referral
  application: referral
  password: "123456"
  incoming_username: foo
  incoming_password: foo


production:
  url: http://nuntium.instedd.org
  account: instedd
  application: MD0-Staging
  password: "dev c0der"
  incoming_username: foo
  incoming_password: foo



test:
  url: http://nuntium.instedd.org
  account: instedd
  application: MD0-Staging
  password: "dev c0der"
  incoming_username: foo
  incoming_password: foo
